allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - astro@6.3.6
  - "@astrojs/internal-helpers@0.10.4"
  - "@astrojs/markdown-remark@7.2.4"
  - "@astrojs/markdown-satteri@0.3.7"
  - "@astrojs/mdx@7.0.7"
  - astro@7.2.4
